# Generated by Django 5.2.7 on 2025-10-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestion',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='correct_answer',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='option_a',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='option_b',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='option_c',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='option_d',
            field=models.TextField(),
        ),
    ]
