# Generated by Django 5.2.7 on 2025-10-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_mcqquestion_sequence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqquestion',
            name='sequence',
        ),
    ]
