# Generated by Django 5.2.7 on 2025-10-31 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0008_rename_title_quiz_quiz_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mcq.category'),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mcq.quiz'),
        ),
    ]
