# Generated by Django 5.2.7 on 2025-10-31 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0009_mcq_category_alter_mcq_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mcq.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mcq',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mcq.quiz'),
        ),
    ]
