# Generated by Django 5.2.7 on 2025-10-31 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0010_alter_mcq_category_alter_mcq_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mcq.category'),
        ),
    ]
