# Generated by Django 5.2.7 on 2025-10-31 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0011_alter_mcq_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mcq.quiz'),
        ),
    ]
